// ─── Application Constants ──────────────────────────────────────────────────

export const SLOT_RESERVATION_TTL_MINUTES = 10;
export const MAX_GROUP_SESSION_PARTICIPANTS = 6;
export const PLATFORM_FEE_PERCENT = 1;

// ─── JWT Constants ──────────────────────────────────────────────────────────

export const JWT_ACCESS_EXPIRY = '15m';
export const JWT_REFRESH_EXPIRY = '7d';
export const JWT_ALGORITHM = 'RS256' as const;

// ─── Rate Limiting ──────────────────────────────────────────────────────────

export const RATE_LIMIT = {
  DEFAULT: { ttl: 60_000, limit: 2000 },
  AUTH: { ttl: 60_000, limit: 30 },
  BOOKING: { ttl: 60_000, limit: 120 },
  VIDEO: { ttl: 60_000, limit: 60 },
} as const;

// ─── Pagination ─────────────────────────────────────────────────────────────

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

// ─── Subscription Tiers ─────────────────────────────────────────────────────

export const SUBSCRIPTION_TIERS = {
  STARTER: {
    name: 'Starter',
    maxProviders: 3,
    maxServices: 10,
    videoMinutesPerMonth: 500,
    customBranding: false,
    calendarSync: false,
  },
  PRACTICE: {
    name: 'Practice',
    maxProviders: 15,
    maxServices: 50,
    videoMinutesPerMonth: 5000,
    customBranding: true,
    calendarSync: true,
  },
  ENTERPRISE: {
    name: 'Enterprise',
    maxProviders: Infinity,
    maxServices: Infinity,
    videoMinutesPerMonth: Infinity,
    customBranding: true,
    calendarSync: true,
  },
} as const;

// ─── Specialty Presets ──────────────────────────────────────────────────────

export const SPECIALTY_PRESETS = {
  PRIMARY_CARE: {
    defaultServices: ['Initial Consultation', 'Follow-up Visit', 'Annual Physical'],
    defaultDurations: [30, 15, 45],
    intakeTemplate: 'general-health',
  },
  MENTAL_HEALTH: {
    defaultServices: ['Initial Assessment', 'Therapy Session', 'Medication Review'],
    defaultDurations: [60, 50, 30],
    intakeTemplate: 'mental-health',
  },
  DENTAL: {
    defaultServices: ['Initial Exam', 'Cleaning', 'Consultation'],
    defaultDurations: [45, 60, 30],
    intakeTemplate: 'dental',
  },
  DERMATOLOGY: {
    defaultServices: ['Skin Consultation', 'Follow-up', 'Cosmetic Consultation'],
    defaultDurations: [30, 15, 30],
    intakeTemplate: 'general-health',
  },
  PHYSICAL_THERAPY: {
    defaultServices: ['Initial Evaluation', 'Therapy Session', 'Progress Review'],
    defaultDurations: [60, 45, 30],
    intakeTemplate: 'general-health',
  },
  SPECIALIST: {
    defaultServices: ['Initial Consultation', 'Follow-up Visit'],
    defaultDurations: [45, 20],
    intakeTemplate: 'general-health',
  },
  OTHER: {
    defaultServices: ['Consultation', 'Follow-up'],
    defaultDurations: [30, 15],
    intakeTemplate: 'general-health',
  },
} as const;

// ─── Audit Actions ──────────────────────────────────────────────────────────

export const AUDIT_ACTIONS = {
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_REGISTER: 'auth.register',
  AUTH_PASSWORD_RESET: 'auth.password_reset',
  PRACTICE_CREATE: 'practice.create',
  PRACTICE_UPDATE: 'practice.update',
  PROVIDER_CREATE: 'provider.create',
  PROVIDER_UPDATE: 'provider.update',
  SERVICE_CREATE: 'service.create',
  SERVICE_UPDATE: 'service.update',
  APPOINTMENT_CREATE: 'appointment.create',
  APPOINTMENT_CANCEL: 'appointment.cancel',
  APPOINTMENT_CONFIRM: 'appointment.confirm',
  APPOINTMENT_COMPLETE: 'appointment.complete',
  VIDEO_ROOM_CREATE: 'video.room_create',
  VIDEO_JOIN: 'video.join',
  VIDEO_LEAVE: 'video.leave',
  MESSAGE_SEND: 'message.send',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_REFUND: 'payment.refund',
  INTAKE_SUBMIT: 'intake.submit',
  MEMBER_INVITE: 'member.invite',
  MEMBER_REMOVE: 'member.remove',
  PATIENT_DATA_EXPORT: 'patient.data_export',
  PATIENT_DATA_VIEW: 'patient.data_view',
  SETTINGS_UPDATE: 'settings.update',
} as const;

// ─── BullMQ Queue Names ────────────────────────────────────────────────────

export const QUEUES = {
  REMINDERS: 'appointment-reminders',
  NOTIFICATIONS: 'notifications',
  CALENDAR_SYNC: 'calendar-sync',
  SLOT_CLEANUP: 'slot-cleanup',
  VIDEO_CLEANUP: 'video-cleanup',
  EMAIL: 'email',
  SMS: 'sms',
} as const;

// ─── Demo Banner ────────────────────────────────────────────────────────────

export const DEMO_DISCLAIMER =
  'Demo application — synthetic data only. Not for clinical use. All patient records are generated by Synthea (MITRE).';
